### ISSUE TITLE
리워드 API payload의 오타 관련 질문

### ISSUE THREAD

**Issue by junbyeol** [linkprice/AffiliateSetup#3]
[이 리워드 API 문서](https://github.com/linkprice/AffiliateSetup/blob/master/docs/%EB%A6%AC%EC%9B%8C%EB%93%9C_%EC%98%A4%ED%94%88_API.md) 의 표와 payload 예시에 따르면, `commission` 이 아닌 `commision`(s가 하나 빠짐)으로 값이 내려온다고 되어있는데요.
실제로도 이렇게 내려오는지 문의드립니다.

**Comment by initNirvana** [comment]
안녕하세요, @junbyeol 님

넵, 말씀하신 해당 `s` 가 빠진 `commision`으로 내려오고 있습니다. :)

해당 상황은 인지하고 있으나 `commision` 으로 이미 연동된 매체가 많이 있어 변경을 하지 못하고 있습니다.

감사합니다.
